// Auth Login
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_START_GOOGLE_LOGIN = 'AUTH_START_GOOGLE_LOGIN';
export const AUTH_START_EMAIL_LOGIN = 'AUTH_START_EMAIL_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGIN_LOGGED_USER = 'AUTH_LOGIN_LOGGED_USER';

// Auth Signup
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';

// Locale
export const LOCALE_SET = 'LOCALE_SET';
export const LOCALE_SET_SUCCESS = 'LOCALE_SET_SUCCESS';

// Reporting
export const REPORT_CHANGE_QUESTION = 'REPORT_CHANGE_QUESTION';

// Find Notification
export const FIND_NOTIFICATION_SET_DATE = 'FIND_NOTIFICATION_SET_DATE';
export const FIND_NOTIFICATION_SET_COORDS = 'FIND_NOTIFICATION_SET_COORDS';
export const FIND_NOTIFICATION_SET_FIND_PHOTOS = 'FIND_NOTIFICATION_SET_FIND_PHOTOS';
export const FIND_NOTIFICATION_SET_FIND_SITE_PHOTOS = 'FIND_NOTIFICATION_SET_FIND_SITE_PHOTOS';
export const FIND_NOTIFICATION_SET_ADDITIONAL_MATERIALS = 'FIND_NOTIFICATION_SET_ADDITIONAL_MATERIALS';
export const FIND_NOTIFICATION_CHANGE_FIND_INDEX = 'FIND_NOTIFICATION_CHANGE_FIND_INDEX';
export const FIND_NOTIFICATION_SET_FIND_TYPE = 'FIND_NOTIFICATION_SET_FIND_TYPE';
export const FIND_NOTIFICATION_SET_FIND_MATERIAL = 'FIND_NOTIFICATION_SET_FIND_MATERIAL';
export const FIND_NOTIFICATION_SET_FIND_TIMING = 'FIND_NOTIFICATION_SET_FIND_TIMING';
export const FIND_NOTIFICATION_SET_FIND_DEPTH = 'FIND_NOTIFICATION_SET_FIND_DEPTH';
export const FIND_NOTIFICATION_SEND = 'FIND_NOTIFICATION_SEND';
export const FIND_NOTIFICATION_SEND_SUCCESS = 'FIND_NOTIFICATION_SEND_SUCCESS';
export const FIND_NOTIFICATION_SEND_FAIL = 'FIND_NOTIFICATION_SEND_FAIL';

// Find
export const FIND_GET_VALIDATED_FINDS = 'FIND_GET_VALIDATED_FINDS';
export const FIND_GET_VALIDATED_SUCCESS = 'FIND_GET_VALIDATED_SUCCESS';
export const FIND_GET_VALIDATED_FAIL = 'FIND_GET_VALIDATED_FAIL';

// Facet Filters
export const FACET_FILTER_SET = 'FACET_FILTER_SET';
export const FACET_FILTER_REMOVE = 'FACET_FILTER_REMOVE';
export const FACET_FILTER_EMPTY = 'FACET_FILTER_EMPTY';

// Notifier
export const NOTIFIER_ENQUEUE_SNACKBAR = 'NOTIFIER_ENQUEUE_SNACKBAR';
export const NOTIFIER_REMOVE_SNACKBAR = 'NOTIFIER_REMOVE_SNACKBAR';
export const NOTIFIER_CHANGE_STATUS = 'NOTIFIER_CHANGE_STATUS';