// Auth Login
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_START_GOOGLE_LOGIN = 'AUTH_START_GOOGLE_LOGIN';
export const AUTH_START_EMAIL_LOGIN = 'AUTH_START_EMAIL_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGIN_LOGGED_USER = 'AUTH_LOGIN_LOGGED_USER';

// Auth Signup
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';

// Locale
export const LOCALE_SET = 'LOCALE_SET';
export const LOCALE_SET_SUCCESS = 'LOCALE_SET_SUCCESS';

// Reporting
export const REPORT_CHANGE_QUESTION = 'REPORT_CHANGE_QUESTION';


// Find Notification
export const FIND_NOTIFICATION_SET_DATE = 'FIND_NOTIFICATION_SET_DATE';
export const FIND_NOTIFICATION_SET_COORDS = 'FIND_NOTIFICATION_SET_COORDS';